### ISSUE TITLE
error parsing grammar from inside vscode tests

### ISSUE THREAD

**Issue by WebFreak001** [microsoft/vscode-textmate#118]
I'm using the vscode extension test runner which came with `yo code` but when trying to call `grammar.tokenizeLine` the following issue happens:

```
     Error: The module '/home/webfreak/dev/code-d/node_modules/oniguruma/build/Release/onig_scanner.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
      at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
      at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
      at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
      at Module.load (internal/modules/cjs/loader.js:602:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
      at Function.Module._load (internal/modules/cjs/loader.js:533:3)
      at Function.Module._load (/usr/share/code-oss/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:49325:33)
      at Function.load (/usr/share/code-oss/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47435:37)
      at Function.load [as _load] (/usr/share/code-oss/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47288:37)
      at Module.require (internal/modules/cjs/loader.js:640:17)
      at require (internal/modules/cjs/helpers.js:20:18)
      at Object.<anonymous> (code-d/node_modules/oniguruma/src/oniguruma.js:3:21)
      at Object.<anonymous> (code-d/node_modules/oniguruma/src/oniguruma.js:116:3)
      at Module._compile (internal/modules/cjs/loader.js:693:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
      at Module.load (internal/modules/cjs/loader.js:602:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
      at Function.Module._load (internal/modules/cjs/loader.js:533:3)
      at Function.Module._load (/usr/share/code-oss/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:49325:33)
      at Function.load (/usr/share/code-oss/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47435:37)
      at Function.load [as _load] (/usr/share/code-oss/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47288:37)
      at Module.require (internal/modules/cjs/loader.js:640:17)
      at require (internal/modules/cjs/helpers.js:20:18)
      at requireFunc (code-d/node_modules/vscode-textmate/release/main.js:23:16)
      at /home/webfreak/dev/code-d/node_modules/vscode-textmate/release/main.js:59:39
      at Object.createOnigString (code-d/node_modules/vscode-textmate/release/main.js:70:39)
      at Grammar.createOnigString (code-d/node_modules/vscode-textmate/release/main.js:2547:30)
      at Grammar._tokenize (code-d/node_modules/vscode-textmate/release/main.js:2642:33)
      at Grammar.tokenizeLine (code-d/node_modules/vscode-textmate/release/main.js:2608:22)
      at fs.readdir.lines.map.line (code-d/test/syntaxes.test.ts:60:47)
      at Array.map (<anonymous>)
      at /home/webfreak/dev/code-d/test/syntaxes.test.ts:60:27
      at Generator.next (<anonymous>)
      at fulfilled (code-d/out/test/syntaxes.test.js:5:58)
```

I tried reinstalling all dependencies and rebuilding them and tried upgrading and downgrading the nodejs version but I can't find any release with NODE_MODULE_VERSION 69 so I can't install the vscode-textmate dependencies compatible for vscode (and with that the vscode extension test runner).

**Comment by jeff-hykin** [comment]
try adding `"node-gyp": "^4.0.0",` in the dependencies of the `package.json`, I believe I had a similar issue before adding that

**Comment by WebFreak001** [comment]
I tried and compiled vscode from source with a few different versions now and it appears to work properly now. Didn't try the node-gyp thing but it just randomly started working. Though it doesn't feel that good that I didn't change anything and just tried different node versions, so other users will have issues with this.

So for now I just put it in a separate test folder which is run from the command line using the normal node and not the vscode electron node. Another advantage is that it can now run from a CI and doesn't need to have vscode so I think that's the way to go anyway.
