### ISSUE TITLE
Variable-width lookbehinds work in VS Code, but not in vscode-textmate

### ISSUE THREAD

**Issue by dustypomerleau** [microsoft/vscode-textmate#142]
Thanks to everyone working hard on vscode-textmate.

Regexes with variable-width lookarounds appear to work well in VS Code grammars, but when I try to test them with @PanAeon's [vscode-tmgrammar-test](https://github.com/PanAeon), I get an error in vscode-textmate:

```bash
Error: invalid pattern in look-behind
    at Object.createOnigScanner (/.../rust-syntax/node_modules/vscode-textmate/release/main.js:67:24)
    at Grammar.createOnigScanner (/.../rust-syntax/node_modules/vscode-textmate/release/main.js:2578:30)
    at RegExpSourceList.compile (/.../rust-syntax/node_modules/vscode-textmate/release/main.js:1875:38)
    at IncludeOnlyRule.compile (/.../rust-syntax/node_modules/vscode-textmate/release/main.js:1974:45)
    at matchRule (/.../rust-syntax/node_modules/vscode-textmate/release/main.js:2822:28)
    at matchRuleOrInjections (/.../rust-syntax/node_modules/vscode-textmate/release/main.js:2841:23)
    at scanNext (/.../rust-syntax/node_modules/vscode-textmate/release/main.js:2937:17)
    at _tokenizeString (/.../rust-syntax/node_modules/vscode-textmate/release/main.js:2930:9)
    at Grammar._tokenize (/.../rust-syntax/node_modules/vscode-textmate/release/main.js:2680:25)
    at Grammar.tokenizeLine (/.../rust-syntax/node_modules/vscode-textmate/release/main.js:2643:22)
The terminal process "/usr/local/bin/zsh '-c', 'npx vscode-tmgrammar-test -c -s source.rust -g syntaxes/rust.tmLanguage.json -t "test/**/*.rs"'" terminated with exit code: 255.
```

For example, the error will appear with:

```
(?<!test\s*)example
```

but is resolved after removing `*`.

I understand that some regex engines require lookarounds to have fixed width, but I don't understand why VS Code is able to process them, but vscode-textmate can't handle them when used as a dependency.

Happy to help fix this if someone can point me in the right direction.

**Comment by jeff-hykin** [comment]
VS Code uses the Oniguruma engine based on ruby's regex. The VS Code search relies on (I believe) ripgrep. The variable width lookbehind is really really bad for performance (fine for 1-time search but not so great when its running with literally every keystroke). But if you want to implement it anyways, probably try to get it changed in Oniguruma https://github.com/atom/node-oniguruma

**Comment by dustypomerleau** [comment]
> variable width lookbehind is really really bad for performance

Ah, I didn't realize. It's very convenient for Textmate grammars because it doesn't consume the pattern (like `\K`), so for wildcard matches you can trust that whatever is present will be highlighted correctly by another section of the grammar. It eliminates the need to define and include lots of repository subsections when you are matching a simple pattern that might occur in a complex context.

But If it's super costly I probably should break the habit now, rather than investing in getting it added to `node-oniguruma`. Thanks for your time.

**Comment by jeff-hykin** [comment]
np 👍  I know its a real pain. For [C++](https://github.com/jeff-hykin/cpp-textmate-grammar) and several other languages I use a beta library that lets me write really complex regex and lookbehinds.

The library is 97% done, but its been kinda stuck that way the last 6 months since I lost a lot of my free time. But if you look at the better-go-syntax, you might be able to fork that an make it work for you. [Relevant file here](https://github.com/jeff-hykin/better-go-syntax/blob/5c60b366de1566849944253ea8a3d6fe26820b9a/source/generate.rb#L50)
