### ISSUE TITLE
Native dependencies cause module version mismatch

### ISSUE THREAD

**Issue by mariosangiorgio** [microsoft/vscode-textmate#43]
I'm trying to use `vscode-textmate` in a language server I'm writing but I'm having troubles with native dependencies.

```
Error: Module version mismatch. Expected 50, got 51.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:178:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:178:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ([...]/node_modules/oniguruma/lib/oniguruma.js:4:17)
```

I'm running Visual Studio code on a Mac (Version 1.11.2) and the version of the library I'm using is: `        "vscode-textmate": "^3.1.4"`

[This `vscode` discussion](https://github.com/Microsoft/vscode/issues/13143) suggests that using native dependencies isn't going to work nicely in general. How does affect this project? Is there any plan or known workaround?

**Comment by alexandrudima** [comment]
`oniguruma` needs to be installed via `npm install` which will compile it against the current version of `node`.
