### ISSUE TITLE
vscode-textmate doesn't build with recent versions of TypeScript

### ISSUE THREAD

**Issue by mvhenderson** [Microsoft/vscode-textmate#53]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:12:42.401Z)
- OS Version: Darwin x64 16.7.0
- Extensions: n/a

To reproduce clone then `npm install`, prepublish step fails (with child_process error from `tsc`).

Reverting to `typescript@2.0.8` (the version in the package.json) fixes the issue.

```
~/Source/vscode
$ git clone git@github.com:Microsoft/vscode-textmate.git
Cloning into 'vscode-textmate'...
remote: Counting objects: 1691, done.
remote: Total 1691 (delta 0), reused 0 (delta 0), pack-reused 1691
Receiving objects: 100% (1691/1691), 2.10 MiB | 2.06 MiB/s, done.
Resolving deltas: 100% (1032/1032), done.

~/Source/vscode
$ cd vscode-textmate/

~/Source/vscode/vscode-textmate master
$ npm install
npm WARN deprecated typings@1.5.0: Typings is deprecated in favor of NPM @types -- see README for more information
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> oniguruma@6.2.1 install /Users/mike/Source/vscode/vscode-textmate/node_modules/oniguruma
> node-gyp rebuild

    ... oniguruma compilation output ...

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> vscode-textmate@3.1.5 prepublish /Users/mike/Source/vscode/vscode-textmate
> node scripts/release.js

child_process.js:634
    throw err;
    ^

Error: Command failed: node node_modules/typescript/bin/tsc
    at checkExecSyncError (child_process.js:591:13)
    at Object.execSync (child_process.js:631:13)
    at Object.<anonymous> (/Users/mike/Source/vscode/vscode-textmate/scripts/release.js:5:4)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-textmate@3.1.5 prepublish: `node scripts/release.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vscode-textmate@3.1.5 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mike/.npm/_logs/2017-09-10T03_21_16_772Z-debug.log

~/Source/vscode/vscode-textmate master
$ node_modules/typescript/bin/tsc --version
Version 2.5.2

~/Source/vscode/vscode-textmate master
$ node_modules/typescript/bin/tsc
src/types.ts(31,2): error TS2411: Property '$vscodeTextmateLocation' of type 'ILocation' is not assignable to string index type 'IRawRule'.
src/types.ts(60,2): error TS2411: Property '$vscodeTextmateLocation' of type 'ILocation' is not assignable to string index type 'IRawRule'.

~/Source/vscode/vscode-textmate master
$ tsc --version
Version 2.4.1

~/Source/vscode/vscode-textmate master
$ tsc
src/types.ts(31,2): error TS2411: Property '$vscodeTextmateLocation' of type 'ILocation' is not assignable to string index type 'IRawRule'.
src/types.ts(60,2): error TS2411: Property '$vscodeTextmateLocation' of type 'ILocation' is not assignable to string index type 'IRawRule'.

~/Source/vscode/vscode-textmate master
$ npm install typescript@2.0.8 --force
npm WARN using --force I sure hope you know what you are doing.
npm notice created a lockfile as package-lock.json. You should commit this file.
+ typescript@2.0.8
updated 1 package in 2.116s

~/Source/vscode/vscode-textmate master ?
$ node_modules/typescript/bin/tsc --version
Version 2.0.8

~/Source/vscode/vscode-textmate master ?
$ node_modules/typescript/bin/tsc

~/Source/vscode/vscode-textmate master ?
$
```

**Comment by alexandrudima** [comment]
Fixed via https://github.com/Microsoft/vscode-textmate/commit/92a639b103a70abe3a30364bcfdbf017cbcf94e0
